In [1]:
# Dependencies and Setup
import json
import pandas as pd
import requests

In [2]:
#Bring in data from internet as object then convert ot Json
schedule_response_obj=requests.get("http://data.nba.net/prod/v1/2018/schedule.json")
schedule_response=schedule_response_obj.json()

In [3]:
# Count # of Games
# schedule_response_count=schedule_response["league"]["standard"]
# schedule_count=len(schedule_response_count)
# schedule_count = 1

In [4]:
# If statement to exclude if tags = "pre-season"
# tags=schedule_response_list["tags"]

#Bring in elements for NBA Schedule
NBA_Schedule=[]
for item in schedule_response["league"]["standard"]:
    item_dict={}
    item_dict["gameID"]=item["gameId"]
    item_dict["startDateEastern"]=item["startDateEastern"]
    item_dict["hTeam"]=item["hTeam"]["teamId"]
    item_dict["vTeam"]=item["vTeam"]["teamId"]
    item_dict["national_broadcast"]=item["watch"]["broadcast"]["video"]["national"]["broadcasters"]
    

    # Create an Object list to store NBA Game Information
    NBA_Schedule.append(item_dict)

In [8]:
NBA_Schedule_DF_initial=pd.DataFrame(NBA_Schedule)
NBA_Schedule_DF=NBA_Schedule_DF_initial[["startDateEastern","gameID","vTeam","hTeam","national_broadcast"]]
NBA_Schedule_DF

,startDateEastern,gameID,vTeam,hTeam,national_broadcast
0,20180928,0011800001,15016,1610612755,[]
1,20180928,0011800002,1610612738,1610612766,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
2,20180929,0011800003,1610612757,1610612761,[]
3,20180929,0011800004,15021,1610612742,[]
4,20180929,0011800005,1610612750,1610612744,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
5,20180929,0011800006,104,1610612762,[]
6,20180930,0011800007,1610612748,1610612759,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
7,20180930,0011800008,1610612766,1610612738,[]
8,20180930,0011800009,1610612740,1610612741,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
9,20180930,0011800010,1610612743,1610612747,"[{'shortName': 'ESPN', 'longName': 'ESPN'}]"
10,20180930,0011800011,15015,1610612746,[]
11,20181001,0011800012,1610612753,1610612755,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
12,20181001,0011800013,1610612752,1610612764,[]
13,20181001,0011800014,1610612740,1610612737,[]
14,20181001,0011800015,1610612758,1610612756,[]
15,20181002,0011800016,1610612748,1610612766,[]
16,20181002,0011800017,1610612739,1610612738,"[{'shortName': 'TNT', 'longName': 'Turner Netw..."
17,20181002,0011800018,1610612763,1610612745,[]
18,20181002,0011800019,1610612761,1610612762,[]
19,20181002,0011800020,1610612743,1610612747,"[{'shortName': 'TNT', 'longName': 'Turner Netw..."
20,20181003,0011800021,1610612752,1610612751,[]
21,20181003,0011800022,1610612741,1610612749,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
22,20181003,0011800023,1610612765,1610612760,[]
23,20181003,0011800024,15020,1610612756,[]
24,20181003,0011800025,1610612750,1610612746,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
25,20181004,0011800026,1610612754,1610612745,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
26,20181004,0011800027,1610612758,1610612747,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
27,20181005,0011800028,1610612755,1610612742,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
28,20181005,0011800029,12325,1610612753,[]
29,20181005,0011800030,15016,1610612761,[]
...,...,...,...,...,...
1279,20190407,0021801200,1610612756,1610612745,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
1280,20190407,0021801202,1610612737,1610612749,[]
1281,20190407,0021801203,1610612753,1610612738,[]
1282,20190407,0021801204,1610612764,1610612752,[]
1283,20190407,0021801205,1610612746,1610612744,"[{'shortName': 'NBA TV', 'longName': 'NBA TV'}]"
1284,20190407,0021801206,1610612743,1610612757,[]
1285,20190407,0021801207,1610612740,1610612758,[]
1286,20190407,0021801208,1610612762,1610612747,[]
1287,20190409,0021801209,1610612766,1610612739,[]
1288,20190409,0021801210,1610612763,1610612765,[]
1289,20190409,0021801211,1610612738,1610612764,"[{'shortName': 'TNT', 'longName': 'Turner Netw..."
1290,20190409,0021801212,1610612755,1610612748,[]
1291,20190409,0021801213,1610612752,1610612741,[]
1292,20190409,0021801214,1610612761,1610612750,[]
1293,20190409,0021801215,1610612744,1610612740,[]
1294,20190409,0021801216,1610612756,1610612742,[]
1295,20190409,0021801217,1610612743,1610612762,[]
1296,20190409,0021801218,1610612745,1610612760,"[{'shortName': 'TNT', 'longName': 'Turner Netw..."
1297,20190409,0021801219,1610612757,1610612747,[]
1298,20190410,0021801220,1610612754,1610612737,[]
1299,20190410,0021801221,1610612748,1610612751,[]
1300,20190410,0021801222,1610612753,1610612766,"[{'shortName': 'ESPN', 'longName': 'ESPN'}]"
1301,20190410,0021801223,1610612765,1610612752,[]
1302,20190410,0021801224,1610612741,1610612755,[]
1303,20190410,0021801225,1610612744,1610612763,[]
1304,20190410,0021801226,1610612760,1610612749,[]
1305,20190410,0021801227,1610612742,1610612759,[]
1306,20190410,0021801228,1610612750,1610612743,"[{'shortName': 'ESPN', 'longName': 'ESPN'}]"
1307,20190410,0021801229,1610612762,1610612746,[]
1308,20190410,0021801230,1610612758,1610612757,[]